
// -----------------------------------------------------------------------

// let fruits = ["Apple", "Banana", "Mango", "Orange"];
// fruits.forEach((fruit )=>{
//     console.log( fruit);
// })



// -----------------------------------------------------------------------


// let fruits = ["Apple", "Banana", "Mango", "Orange"];
// fruits.forEach((fruit,index)=>{
//     console.log(index,fruit);
// })



// -----------------------------------------------------------------------

// let arr1 = [1,2,3,4,5,6,7]
// let total = 0;
// arr1.forEach((num)=>{
//    total+=num;   
// })
// console.log(total);



 // -----------------------------------------------------------------------


//  let prices = [100,200,300]
//  let total = 0;
// prices.forEach((price)=>{
//     total+=price
// })
// console.log(`the total price is $${total}`);


// let names = ["suleman","shawaiz","salman"]
// let capital = []
// names.forEach((name)=>{
//     capital.push(name.toLocaleUpperCase())
    
//     })
// console.log(capital);



// -----------------------------------------------------------------------
// let numbers = [1,2,3,4,5,6,7,8,9,10]
// numbers.forEach((num)=>{
//   let mul = num*5;
//  console.log(`5 x ${num} = ${mul}`);
// });



// let objs = [{name:"suleman"},{age: 19 },{ firstName : "Mohd  "}]
// let objs1 = {}
// objs.forEach((obj)=>{
// console.log(obj.name);
     

// })

// let scores = [92,35,67,96,32,45]
// scores.forEach((score)=>{
//     if(score>80){
//         console.log("excellent");
//     }
//     else{
//         console.log("keep trying");
//     }
// })


 

